//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class db_Attendance
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int courseID { get; set; }
        public int studID { get; set; }
    
        public virtual course course { get; set; }
        public virtual person person { get; set; }
    }
}
