//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.db_Attendance = new HashSet<db_Attendance>();
            this.student_course = new HashSet<student_course>();
            this.Teaacher_course = new HashSet<Teaacher_course>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool gender { get; set; }
        public bool C_isadmin { get; set; }
        public bool C_isteacher { get; set; }
        public bool C_isstudent { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int age { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public int grade { get; set; }
        public byte[] picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<db_Attendance> db_Attendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_course> student_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teaacher_course> Teaacher_course { get; set; }
    }
}
