using Bunifu.Framework.UI;

namespace DesktopApp3
{
    partial class Profile
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Profile));
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox.StateProperties();
            this.male = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.Female = new Bunifu.UI.WinForms.BunifuRadioButton();
            this.panel1 = new System.Windows.Forms.Panel();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.name_profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Age_Profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Phone_Profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Address_profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Email_Profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Password_Profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.Grade_profile = new Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // male
            // 
            this.male.Checked = true;
            this.male.Enabled = false;
            this.male.Location = new System.Drawing.Point(51, 347);
            this.male.Name = "male";
            this.male.OutlineColor = System.Drawing.Color.PaleVioletRed;
            this.male.RadioColor = System.Drawing.Color.Crimson;
            this.male.Size = new System.Drawing.Size(19, 19);
            this.male.TabIndex = 28;
            this.male.Text = null;
            // 
            // Female
            // 
            this.Female.Checked = false;
            this.Female.Enabled = false;
            this.Female.Location = new System.Drawing.Point(184, 347);
            this.Female.Name = "Female";
            this.Female.OutlineColor = System.Drawing.Color.PaleVioletRed;
            this.Female.RadioColor = System.Drawing.Color.Crimson;
            this.Female.Size = new System.Drawing.Size(19, 19);
            this.Female.TabIndex = 29;
            this.Female.Text = null;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.panel1.Controls.Add(this.Grade_profile);
            this.panel1.Controls.Add(this.Password_Profile);
            this.panel1.Controls.Add(this.Email_Profile);
            this.panel1.Controls.Add(this.Address_profile);
            this.panel1.Controls.Add(this.Phone_Profile);
            this.panel1.Controls.Add(this.Age_Profile);
            this.panel1.Controls.Add(this.name_profile);
            this.panel1.Controls.Add(this.bunifuPictureBox1);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.bunifuButton2);
            this.panel1.Controls.Add(this.bunifuButton1);
            this.panel1.Controls.Add(this.Female);
            this.panel1.Controls.Add(this.male);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(579, 405);
            this.panel1.TabIndex = 0;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Enabled = false;
            this.label2.Font = new System.Drawing.Font("Arial", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.GhostWhite;
            this.label2.Location = new System.Drawing.Point(209, 347);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(55, 16);
            this.label2.TabIndex = 37;
            this.label2.Text = "Female";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Enabled = false;
            this.label1.Font = new System.Drawing.Font("Arial", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.GhostWhite;
            this.label1.Location = new System.Drawing.Point(76, 347);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(38, 16);
            this.label1.TabIndex = 36;
            this.label1.Text = "Male";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.BorderRadius = 50;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(448, 28);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(100, 100);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 38;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "   Edit Info";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges1;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleBorderRadius = 3;
            this.bunifuButton2.IdleBorderThickness = 10;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.IdleIconLeftImage = global::DesktopApp3.Properties.Resources.icons8_autograph_1;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(431, 354);
            this.bunifuButton2.Name = "bunifuButton2";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.BorderRadius = 3;
            stateProperties29.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties29.BorderThickness = 10;
            stateProperties29.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties29.ForeColor = System.Drawing.Color.White;
            stateProperties29.IconLeftImage = null;
            stateProperties29.IconRightImage = null;
            this.bunifuButton2.onHoverState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.BorderRadius = 3;
            stateProperties30.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties30.BorderThickness = 10;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties30.ForeColor = System.Drawing.Color.White;
            stateProperties30.IconLeftImage = null;
            stateProperties30.IconRightImage = null;
            this.bunifuButton2.OnPressedState = stateProperties30;
            this.bunifuButton2.Size = new System.Drawing.Size(139, 35);
            this.bunifuButton2.TabIndex = 35;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click_1);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "   Choose Photo";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges2;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleBorderRadius = 3;
            this.bunifuButton1.IdleBorderThickness = 10;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.IdleIconLeftImage = global::DesktopApp3.Properties.Resources.icons8_change;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(431, 139);
            this.bunifuButton1.Name = "bunifuButton1";
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.BorderRadius = 3;
            stateProperties31.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties31.BorderThickness = 10;
            stateProperties31.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.ForeColor = System.Drawing.Color.White;
            stateProperties31.IconLeftImage = null;
            stateProperties31.IconRightImage = null;
            this.bunifuButton1.onHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties32.BorderRadius = 3;
            stateProperties32.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties32.BorderThickness = 10;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.IconLeftImage = null;
            stateProperties32.IconRightImage = null;
            this.bunifuButton1.OnPressedState = stateProperties32;
            this.bunifuButton1.Size = new System.Drawing.Size(139, 35);
            this.bunifuButton1.TabIndex = 34;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // name_profile
            // 
            this.name_profile.AcceptsReturn = false;
            this.name_profile.AcceptsTab = false;
            this.name_profile.AnimationSpeed = 200;
            this.name_profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.name_profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.name_profile.BackColor = System.Drawing.Color.Transparent;
            this.name_profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("name_profile.BackgroundImage")));
            this.name_profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.name_profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.name_profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.name_profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.name_profile.BorderRadius = 20;
            this.name_profile.BorderThickness = 1;
            this.name_profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.name_profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.name_profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.name_profile.DefaultText = "";
            this.name_profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.name_profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.name_profile.HideSelection = true;
            this.name_profile.IconLeft = null;
            this.name_profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.name_profile.IconPadding = 10;
            this.name_profile.IconRight = null;
            this.name_profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.name_profile.Lines = new string[0];
            this.name_profile.Location = new System.Drawing.Point(45, 40);
            this.name_profile.MaxLength = 32767;
            this.name_profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.name_profile.Modified = false;
            this.name_profile.Multiline = false;
            this.name_profile.Name = "name_profile";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_profile.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Empty;
            stateProperties26.FillColor = System.Drawing.Color.White;
            stateProperties26.ForeColor = System.Drawing.Color.Empty;
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.name_profile.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_profile.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties28.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.name_profile.OnIdleState = stateProperties28;
            this.name_profile.PasswordChar = '\0';
            this.name_profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.name_profile.PlaceholderText = "Enter Name";
            this.name_profile.ReadOnly = true;
            this.name_profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.name_profile.SelectedText = "";
            this.name_profile.SelectionLength = 0;
            this.name_profile.SelectionStart = 0;
            this.name_profile.ShortcutsEnabled = true;
            this.name_profile.Size = new System.Drawing.Size(272, 35);
            this.name_profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.name_profile.TabIndex = 55;
            this.name_profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.name_profile.TextMarginBottom = 0;
            this.name_profile.TextMarginLeft = 5;
            this.name_profile.TextMarginTop = 0;
            this.name_profile.TextPlaceholder = "Enter Name";
            this.name_profile.UseSystemPasswordChar = false;
            this.name_profile.WordWrap = true;
            this.name_profile.TextChanged += new System.EventHandler(this.name_profile_TextChanged);
            // 
            // Age_Profile
            // 
            this.Age_Profile.AcceptsReturn = false;
            this.Age_Profile.AcceptsTab = false;
            this.Age_Profile.AnimationSpeed = 200;
            this.Age_Profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Age_Profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Age_Profile.BackColor = System.Drawing.Color.Transparent;
            this.Age_Profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Age_Profile.BackgroundImage")));
            this.Age_Profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Age_Profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Age_Profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Age_Profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Age_Profile.BorderRadius = 20;
            this.Age_Profile.BorderThickness = 1;
            this.Age_Profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Age_Profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Age_Profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Age_Profile.DefaultText = "";
            this.Age_Profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Age_Profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Age_Profile.HideSelection = true;
            this.Age_Profile.IconLeft = null;
            this.Age_Profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Age_Profile.IconPadding = 10;
            this.Age_Profile.IconRight = null;
            this.Age_Profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Age_Profile.Lines = new string[0];
            this.Age_Profile.Location = new System.Drawing.Point(45, 81);
            this.Age_Profile.MaxLength = 32767;
            this.Age_Profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Age_Profile.Modified = false;
            this.Age_Profile.Multiline = false;
            this.Age_Profile.Name = "Age_Profile";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Age_Profile.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.Empty;
            stateProperties22.FillColor = System.Drawing.Color.White;
            stateProperties22.ForeColor = System.Drawing.Color.Empty;
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Age_Profile.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Age_Profile.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties24.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Age_Profile.OnIdleState = stateProperties24;
            this.Age_Profile.PasswordChar = '\0';
            this.Age_Profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Age_Profile.PlaceholderText = "Enter Age";
            this.Age_Profile.ReadOnly = true;
            this.Age_Profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Age_Profile.SelectedText = "";
            this.Age_Profile.SelectionLength = 0;
            this.Age_Profile.SelectionStart = 0;
            this.Age_Profile.ShortcutsEnabled = true;
            this.Age_Profile.Size = new System.Drawing.Size(272, 35);
            this.Age_Profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Age_Profile.TabIndex = 62;
            this.Age_Profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Age_Profile.TextMarginBottom = 0;
            this.Age_Profile.TextMarginLeft = 5;
            this.Age_Profile.TextMarginTop = 0;
            this.Age_Profile.TextPlaceholder = "Enter Age";
            this.Age_Profile.UseSystemPasswordChar = false;
            this.Age_Profile.WordWrap = true;
            this.Age_Profile.TextChanged += new System.EventHandler(this.Age_Profile_TextChanged);
            // 
            // Phone_Profile
            // 
            this.Phone_Profile.AcceptsReturn = false;
            this.Phone_Profile.AcceptsTab = false;
            this.Phone_Profile.AnimationSpeed = 200;
            this.Phone_Profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Phone_Profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Phone_Profile.BackColor = System.Drawing.Color.Transparent;
            this.Phone_Profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Phone_Profile.BackgroundImage")));
            this.Phone_Profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Phone_Profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Phone_Profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Phone_Profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Phone_Profile.BorderRadius = 20;
            this.Phone_Profile.BorderThickness = 1;
            this.Phone_Profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Phone_Profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Phone_Profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Phone_Profile.DefaultText = "";
            this.Phone_Profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Phone_Profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Phone_Profile.HideSelection = true;
            this.Phone_Profile.IconLeft = null;
            this.Phone_Profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Phone_Profile.IconPadding = 10;
            this.Phone_Profile.IconRight = null;
            this.Phone_Profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Phone_Profile.Lines = new string[0];
            this.Phone_Profile.Location = new System.Drawing.Point(45, 122);
            this.Phone_Profile.MaxLength = 32767;
            this.Phone_Profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Phone_Profile.Modified = false;
            this.Phone_Profile.Multiline = false;
            this.Phone_Profile.Name = "Phone_Profile";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Phone_Profile.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.Empty;
            stateProperties18.FillColor = System.Drawing.Color.White;
            stateProperties18.ForeColor = System.Drawing.Color.Empty;
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Phone_Profile.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Phone_Profile.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties20.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Phone_Profile.OnIdleState = stateProperties20;
            this.Phone_Profile.PasswordChar = '\0';
            this.Phone_Profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Phone_Profile.PlaceholderText = "Enter Phone";
            this.Phone_Profile.ReadOnly = true;
            this.Phone_Profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Phone_Profile.SelectedText = "";
            this.Phone_Profile.SelectionLength = 0;
            this.Phone_Profile.SelectionStart = 0;
            this.Phone_Profile.ShortcutsEnabled = true;
            this.Phone_Profile.Size = new System.Drawing.Size(272, 35);
            this.Phone_Profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Phone_Profile.TabIndex = 63;
            this.Phone_Profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Phone_Profile.TextMarginBottom = 0;
            this.Phone_Profile.TextMarginLeft = 5;
            this.Phone_Profile.TextMarginTop = 0;
            this.Phone_Profile.TextPlaceholder = "Enter Phone";
            this.Phone_Profile.UseSystemPasswordChar = false;
            this.Phone_Profile.WordWrap = true;
            this.Phone_Profile.TextChanged += new System.EventHandler(this.Phone_Profile_TextChanged);
            // 
            // Address_profile
            // 
            this.Address_profile.AcceptsReturn = false;
            this.Address_profile.AcceptsTab = false;
            this.Address_profile.AnimationSpeed = 200;
            this.Address_profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Address_profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Address_profile.BackColor = System.Drawing.Color.Transparent;
            this.Address_profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Address_profile.BackgroundImage")));
            this.Address_profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Address_profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Address_profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Address_profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Address_profile.BorderRadius = 20;
            this.Address_profile.BorderThickness = 1;
            this.Address_profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Address_profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Address_profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Address_profile.DefaultText = "";
            this.Address_profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Address_profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Address_profile.HideSelection = true;
            this.Address_profile.IconLeft = null;
            this.Address_profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Address_profile.IconPadding = 10;
            this.Address_profile.IconRight = null;
            this.Address_profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Address_profile.Lines = new string[0];
            this.Address_profile.Location = new System.Drawing.Point(45, 163);
            this.Address_profile.MaxLength = 32767;
            this.Address_profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Address_profile.Modified = false;
            this.Address_profile.Multiline = false;
            this.Address_profile.Name = "Address_profile";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Address_profile.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.Empty;
            stateProperties14.FillColor = System.Drawing.Color.White;
            stateProperties14.ForeColor = System.Drawing.Color.Empty;
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Address_profile.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Address_profile.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties16.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Address_profile.OnIdleState = stateProperties16;
            this.Address_profile.PasswordChar = '\0';
            this.Address_profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Address_profile.PlaceholderText = "Enter Address";
            this.Address_profile.ReadOnly = true;
            this.Address_profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Address_profile.SelectedText = "";
            this.Address_profile.SelectionLength = 0;
            this.Address_profile.SelectionStart = 0;
            this.Address_profile.ShortcutsEnabled = true;
            this.Address_profile.Size = new System.Drawing.Size(272, 35);
            this.Address_profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Address_profile.TabIndex = 64;
            this.Address_profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Address_profile.TextMarginBottom = 0;
            this.Address_profile.TextMarginLeft = 5;
            this.Address_profile.TextMarginTop = 0;
            this.Address_profile.TextPlaceholder = "Enter Address";
            this.Address_profile.UseSystemPasswordChar = false;
            this.Address_profile.WordWrap = true;
            this.Address_profile.TextChanged += new System.EventHandler(this.Address_profile_TextChanged);
            // 
            // Email_Profile
            // 
            this.Email_Profile.AcceptsReturn = false;
            this.Email_Profile.AcceptsTab = false;
            this.Email_Profile.AnimationSpeed = 200;
            this.Email_Profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Email_Profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Email_Profile.BackColor = System.Drawing.Color.Transparent;
            this.Email_Profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Email_Profile.BackgroundImage")));
            this.Email_Profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Email_Profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Email_Profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Email_Profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Email_Profile.BorderRadius = 20;
            this.Email_Profile.BorderThickness = 1;
            this.Email_Profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Email_Profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Email_Profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Email_Profile.DefaultText = "";
            this.Email_Profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Email_Profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Email_Profile.HideSelection = true;
            this.Email_Profile.IconLeft = null;
            this.Email_Profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Email_Profile.IconPadding = 10;
            this.Email_Profile.IconRight = null;
            this.Email_Profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Email_Profile.Lines = new string[0];
            this.Email_Profile.Location = new System.Drawing.Point(45, 204);
            this.Email_Profile.MaxLength = 32767;
            this.Email_Profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Email_Profile.Modified = false;
            this.Email_Profile.Multiline = false;
            this.Email_Profile.Name = "Email_Profile";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Email_Profile.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Empty;
            stateProperties10.FillColor = System.Drawing.Color.White;
            stateProperties10.ForeColor = System.Drawing.Color.Empty;
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Email_Profile.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Email_Profile.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties12.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Email_Profile.OnIdleState = stateProperties12;
            this.Email_Profile.PasswordChar = '\0';
            this.Email_Profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Email_Profile.PlaceholderText = "Enter Email";
            this.Email_Profile.ReadOnly = true;
            this.Email_Profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Email_Profile.SelectedText = "";
            this.Email_Profile.SelectionLength = 0;
            this.Email_Profile.SelectionStart = 0;
            this.Email_Profile.ShortcutsEnabled = true;
            this.Email_Profile.Size = new System.Drawing.Size(272, 35);
            this.Email_Profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Email_Profile.TabIndex = 65;
            this.Email_Profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Email_Profile.TextMarginBottom = 0;
            this.Email_Profile.TextMarginLeft = 5;
            this.Email_Profile.TextMarginTop = 0;
            this.Email_Profile.TextPlaceholder = "Enter Email";
            this.Email_Profile.UseSystemPasswordChar = false;
            this.Email_Profile.WordWrap = true;
            this.Email_Profile.TextChanged += new System.EventHandler(this.Email_Profile_TextChanged);
            // 
            // Password_Profile
            // 
            this.Password_Profile.AcceptsReturn = false;
            this.Password_Profile.AcceptsTab = false;
            this.Password_Profile.AnimationSpeed = 200;
            this.Password_Profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Password_Profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Password_Profile.BackColor = System.Drawing.Color.Transparent;
            this.Password_Profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Password_Profile.BackgroundImage")));
            this.Password_Profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Password_Profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Password_Profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Password_Profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Password_Profile.BorderRadius = 20;
            this.Password_Profile.BorderThickness = 1;
            this.Password_Profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Password_Profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Password_Profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Password_Profile.DefaultText = "";
            this.Password_Profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Password_Profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Password_Profile.HideSelection = true;
            this.Password_Profile.IconLeft = null;
            this.Password_Profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password_Profile.IconPadding = 10;
            this.Password_Profile.IconRight = null;
            this.Password_Profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Password_Profile.Lines = new string[0];
            this.Password_Profile.Location = new System.Drawing.Point(45, 245);
            this.Password_Profile.MaxLength = 32767;
            this.Password_Profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Password_Profile.Modified = false;
            this.Password_Profile.Multiline = false;
            this.Password_Profile.Name = "Password_Profile";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password_Profile.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Empty;
            stateProperties6.FillColor = System.Drawing.Color.White;
            stateProperties6.ForeColor = System.Drawing.Color.Empty;
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Password_Profile.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password_Profile.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties8.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Password_Profile.OnIdleState = stateProperties8;
            this.Password_Profile.PasswordChar = '\0';
            this.Password_Profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Password_Profile.PlaceholderText = "Enter Password";
            this.Password_Profile.ReadOnly = true;
            this.Password_Profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Password_Profile.SelectedText = "";
            this.Password_Profile.SelectionLength = 0;
            this.Password_Profile.SelectionStart = 0;
            this.Password_Profile.ShortcutsEnabled = true;
            this.Password_Profile.Size = new System.Drawing.Size(272, 35);
            this.Password_Profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Password_Profile.TabIndex = 66;
            this.Password_Profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Password_Profile.TextMarginBottom = 0;
            this.Password_Profile.TextMarginLeft = 5;
            this.Password_Profile.TextMarginTop = 0;
            this.Password_Profile.TextPlaceholder = "Enter Password";
            this.Password_Profile.UseSystemPasswordChar = false;
            this.Password_Profile.WordWrap = true;
            this.Password_Profile.TextChanged += new System.EventHandler(this.Password_Profile_TextChanged);
            // 
            // Grade_profile
            // 
            this.Grade_profile.AcceptsReturn = false;
            this.Grade_profile.AcceptsTab = false;
            this.Grade_profile.AnimationSpeed = 200;
            this.Grade_profile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Grade_profile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Grade_profile.BackColor = System.Drawing.Color.Transparent;
            this.Grade_profile.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Grade_profile.BackgroundImage")));
            this.Grade_profile.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Grade_profile.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(161)))), ((int)(((byte)(161)))), ((int)(((byte)(161)))));
            this.Grade_profile.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Grade_profile.BorderColorIdle = System.Drawing.Color.Silver;
            this.Grade_profile.BorderRadius = 20;
            this.Grade_profile.BorderThickness = 1;
            this.Grade_profile.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Grade_profile.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Grade_profile.DefaultFont = new System.Drawing.Font("Segoe UI Semibold", 9.75F);
            this.Grade_profile.DefaultText = "";
            this.Grade_profile.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            this.Grade_profile.ForeColor = System.Drawing.Color.GhostWhite;
            this.Grade_profile.HideSelection = true;
            this.Grade_profile.IconLeft = null;
            this.Grade_profile.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Grade_profile.IconPadding = 10;
            this.Grade_profile.IconRight = null;
            this.Grade_profile.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Grade_profile.Lines = new string[0];
            this.Grade_profile.Location = new System.Drawing.Point(45, 286);
            this.Grade_profile.MaxLength = 32767;
            this.Grade_profile.MinimumSize = new System.Drawing.Size(100, 35);
            this.Grade_profile.Modified = false;
            this.Grade_profile.Multiline = false;
            this.Grade_profile.Name = "Grade_profile";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Grade_profile.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Empty;
            stateProperties2.FillColor = System.Drawing.Color.White;
            stateProperties2.ForeColor = System.Drawing.Color.Empty;
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Grade_profile.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Grade_profile.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(34)))), ((int)(((byte)(36)))), ((int)(((byte)(49)))));
            stateProperties4.ForeColor = System.Drawing.Color.GhostWhite;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Grade_profile.OnIdleState = stateProperties4;
            this.Grade_profile.PasswordChar = '\0';
            this.Grade_profile.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.Grade_profile.PlaceholderText = "Enter Grade";
            this.Grade_profile.ReadOnly = true;
            this.Grade_profile.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Grade_profile.SelectedText = "";
            this.Grade_profile.SelectionLength = 0;
            this.Grade_profile.SelectionStart = 0;
            this.Grade_profile.ShortcutsEnabled = true;
            this.Grade_profile.Size = new System.Drawing.Size(272, 35);
            this.Grade_profile.Style = Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox._Style.Bunifu;
            this.Grade_profile.TabIndex = 67;
            this.Grade_profile.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Grade_profile.TextMarginBottom = 0;
            this.Grade_profile.TextMarginLeft = 5;
            this.Grade_profile.TextMarginTop = 0;
            this.Grade_profile.TextPlaceholder = "Enter Grade";
            this.Grade_profile.UseSystemPasswordChar = false;
            this.Grade_profile.WordWrap = true;
            this.Grade_profile.TextChanged += new System.EventHandler(this.Grade_profile_TextChanged);
            // 
            // Profile
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.panel1);
            this.Name = "Profile";
            this.Size = new System.Drawing.Size(579, 405);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuRadioButton male;
        private Bunifu.UI.WinForms.BunifuRadioButton Female;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Grade_profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Password_Profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Email_Profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Address_profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Phone_Profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox Age_Profile;
        private Bunifu.UI.WinForms.BunifuTextbox.BunifuTextBox name_profile;
    }
}
